### ISSUE TITLE
User Name does not allow Spaces

### ISSUE THREAD

**Issue by tayvermtos** [tksh164/alter-rdp-client#43]
Hi

I tested the the new RDP tool. The username does not allow you to use a username which is made out of more than one word. As soon as you enter more then one name in the username box, the connect button greys out.

**Comment by tksh164** [comment]
@tayvermtos - Thank you for reporting this. It fixed in [Alter v0.2.0](https://github.com/tksh164/alter-rdp-client/releases/tag/v0.2.0)
